### ISSUE TITLE
Accepting suggestions for the loading indicator attribute name

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/documentation#15]
Here's a pull request by @wajahatch888 waiting to be merged for a loading indicator: https://github.com/Jasonette/JASONETTE-iOS/pull/87

I've tried it and it works awesome. One thing I want to make sure is we name this attribute the best way possible. So far we're calling it `loading`, which looks like this:

## For `href`

```
{
  "type": "label",
  "text": "Go",
  "href": {
    "url": "https://....",
    "loading": "true"
  }
}
```

## For `$network.request`

```
{
  "type": "$network.request",
  "options": {
    "url": "https://...."
    "loading": "true"
  }
}
```

The question is:  **Can we come up with a better naming than `loading`?**

Please feel free to share ideas if anyone has a better name suggestion for this attribute. Thanks!

**Comment by lukeramsden** [comment]
NativeScript uses [ActivityIndicator](http://docs.nativescript.org/tutorial/chapter-4#46-activityindicator), maybe could use something like that? Maybe loadingIndicator?

**Comment by wajahatch888** [comment]
I think we should go with `loading` for now because in future i will also add some loading customising feature so it will become
`loading:{
  backgroundColor: "red",
  text : "Loading..",
  show : "true".
  ......

}`

**Comment by lukeramsden** [comment]
@wajahatch888 All the more reason to use something more object-like, so I think we should go with LoadingIndicator or LoadingIcon etc

**Comment by gliechtenstein** [comment]
@lukeramsden while I think both `loadingindicator` and `loadingicon` are fine in their own ways, I will have to disagree with you on this. The reason these other frameworks use camel case class names is because they actually **are** classes. That's not the case for Jasonette, which means there's no reason to artificially make it camel cased. Also it goes against the convention rest of the JASON syntax follows

Here's an unofficial rule of thumb I've been personally abiding by since I began working on Jasonette:
1. When stuck, see if there's a web-standards equivalent (or similar) where I can take inspiration from - I took a lot of inspiration from HTML/Javascript/CSS (and even jQuery and node.js). That said, this is not an absolute. You'll find that JASON syntax doesn't always follow web standards because some web standards tags are unintuitive and don't make sense in Jasonette context. This is why I have a couple more rules I take into account:
2. When stuck between multiple options, pick the one that's most memorable
    A. consistency : Being consistent with rest of the syntax makes it easier to remember
    B. simplicity: Making it as short as possible (while not sacrificing the semantics) makes it easier to remember
3. When stuck between multiple options, the one that's most user-friendly (NOT developer friendly) always should win. (which means even if these were actually implemented as classes--which they are not--we should encapsulate them to make them human-friendly and don't impose the internal class names onto users)

By 'user' I mean anyone who writes the JSON markup, and by 'developer' I mean the developers who work on the core Jasonette native code (iOS/Android/etc.) This means potentially the "users" can be anyone from a seasoned programmer to someone with no previous programming experience.

`loading` fits into two categories--it's simple and easier to type so more use-friendly, but it's not perfect because it can mean anything (it can mean it's currently loading, or that we should display a loading indicator). A perfect solution would be simple yet intuitive enough that anyone looking at the markup would immediately be able to get "oh so it means it's going to display a loading indicator!".

`loadingindicator` or `loadingicon` is more descriptive (pros) but not as simple as `loading` (cons). 

`LoadingIndicator` or `LoadingIcon` with camel case enforcement is not user friendly since it introduces another mental hurdle to remember what to capitalize and what not to. Users shouldn't have to know what "classes" or "objects" are. They should be simply writing tags to describe what the app looks like and how it should behave.

(On a sidenote, going forward I think we should make these attributes case-insensitive just like how HTML tags have evolved into for the sake of user-friendliness.)

Maybe there's something as simple as `loading` yet more descriptive? (`loading` can mean anything)--This was what I was looking for. And would be even better if there's some sort of inspiration we can take from existing web standards.

Anyway, for now `loading` is the top contender. But please do share if you have good ideas.

**Comment by wajahatch888** [comment]
@gliechtenstein , what if we use `loader` instead of `loading` ?

**Comment by lukeramsden** [comment]
@ethan needs closing?
