### ISSUE TITLE
Documentation for loading indicator

### ISSUE THREAD

**Issue by lukeramsden** [Jasonette/documentation#16]
@wajahatch888 maybe you could write it?

**Comment by wajahatch888** [comment]
@lukeramsden , I never tried MkDocs and Travis CI before. i am total newbie. I'll find some time and will definitely try to write it.

**Comment by lukeramsden** [comment]
You just edit the .md files, you'll see how they are laid out by looking at the source 😊

**Comment by gliechtenstein** [comment]
@wajahatch888 Yup, like @lukeramsden said, all you need to do is edit the source. In this case https://github.com/Jasonette/documentation/blob/master/docs/document.md => Which will turn into https://jasonette.github.io/documentation/document/#body All the MkDocs compilation and Travis CI is taken care of automatically when the pull request is merged so you don't have to worry about these things. (Although you can try `mkdocs serve` on your local just to see how it would look before pushing)

**Comment by gliechtenstein** [comment]
Resolved https://github.com/Jasonette/documentation/commit/579ed8fa103fdbd962b4544ab12b60c886c77bb3
