### ISSUE TITLE
Keyboard type

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/documentation#72]
Just like HTML has multiple input types, support multiple input types for the keyboard when `textfield` or `textarea` is focused.

This feature will be triggered by supporting an additional attribute called `keyboard` (tentative) to `textarea` and `textfield` components. Example:

```
{
  "type": "textfield",
  "name": "phone_num",
  "keyboard": "phone"
}
```

For starters I think the following will be enough:

- text (default)
- number
- phone
- email
- url

But any suggestion is welcome, including the attribute name.

**Comment by maks** [comment]
:+1: This is a great idea!
On Android its often useful to turn off auto-complete (aka suggestons). Its just [a couple of other text attributes to set](https://stackoverflow.com/a/33320606/85472)

**Comment by drwasho** [comment]
Hell yes, please!

**Comment by gliechtenstein** [comment]
@maks your comment reminded me that I only implemented some of the attributes such as `autocorrect `, `autocapitalize`, and `spellcheck` on iOS and forgot to do so on Android, as mentioned at http://docs.jasonette.com/components/#textfield 

I just created an issue here: https://github.com/Jasonette/JASONETTE-Android/issues/153

**Comment by gliechtenstein** [comment]
Test case: https://jasonbase.com/things/B8e5

```
{
  "$jason": {
    "head": {
      "title": "keyboard test",
      "data": {
        "types": [
          "text",
          "number",
          "email",
          "phone",
          "url"
        ]
      },
      "templates": {
        "body": {
          "header": {
            "title": "Keyboard test"
          },
          "sections": {
            "{{#each types}}": {
              "header": {
                "type": "label",
                "style": {
                  "background": "#ebebeb"
                },
                "text": "{{this}}"
              },
              "items": [
                {
                  "type": "vertical",
                  "components": [
                    {
                      "type": "textarea",
                      "style": {
                        "align": "left"
                      },
                      "name": "{{this}}_textarea",
                      "placeholder": "{{this}} textarea",
                      "keyboard": "{{this}}"
                    },
                    {
                      "type": "space",
                      "style": {
                        "background": "#ebebeb",
                        "height": "1"
                      }
                    },
                    {
                      "type": "textfield",
                      "name": "{{this}}_textfield",
                      "placeholder": "{{this}} textfield",
                      "keyboard": "{{this}}"
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

**Comment by gliechtenstein** [comment]
Just pushed a PR for this for iOS : https://github.com/Jasonette/JASONETTE-iOS/pull/259

**Comment by gliechtenstein** [comment]
Android PR: https://github.com/Jasonette/JASONETTE-Android/pull/184

**Comment by gliechtenstein** [comment]
Resolved

**Comment by gliechtenstein** [comment]
Documented here: http://docs.jasonette.com/components/#textfield
