### ISSUE TITLE
[Request] Add ios and android attribute to options

### ISSUE THREAD

**Issue by clsource** [Jasonette/documentation#83]
Needed if you want a specific behaviour or style depending on the operating system. Inside each you could put an an object with an action and/or style that would overwrite the global action or style for the component.

```
{
"type" : "button",
"text" : "Click",
"style" : {
  "background" : "#3c3c3c",
  "color" : "#cccccc"
},
"options" : {
  "ios" : {
     "style" : {
       "background" : "#000000"
     }
   },
  "android" : {
     "style" : {
       "color" : "#ffffff"
    }
   }
 }
}
```

**Comment by maks** [comment]
@clsource I think this is another candidate to move over to the new Jasonette (spec) repo issues. I have feedback o this, so I'll wait to add it once its moved to the new repo.
