### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ajmeese7** [Jasonette/documentation#92]
For the `Here's the site` link on https://docs.jasonette.com/agents/, the link doesn't lead to a functioning app. I would have removed the link in a PR, but I feel it would be more beneficial to find a way to offer the code to the users if you don't want to host it so they can try it themselves.

The link right after it, https://wsjason.herokuapp.com/app.json, says it is supposed to be used for that purpose, but it is dead too.

**Comment by clsource** [comment]
go here https://github.com/jasonelle/jasonette-docs/blob/master/docs/agents.md

**Comment by ajmeese7** [comment]
Made this before joining the Slack and learning that this project had been moved to Jasonelle. Apologies
